### ISSUE TITLE
One host but multiple ports

### ISSUE THREAD

**Issue by hkroger** [qvantel/sbt-mobilizer#4]
How should one handle the situation where all nodes where the code is being deployed are behind same host but in different ports (behind NAT basically)?

**Comment by liff** [comment]
How about deprecating the `DeploymentEnvironment.port` and teaching `host:port` syntax for `DeploymentEnvironment.hosts` (with default to `.port`)?

**Comment by hkroger** [comment]
Sounds good to me

**Comment by liff** [comment]
Published 0.2.0.
